/**
 * Liste des icônes Lucide React les plus courantes pour les services
 * Format: { value: 'nom-icone', label: 'Libellé affichable' }
 */

export const availableIcons = [
  { value: 'code', label: 'Code' },
  { value: 'smartphone', label: 'Smartphone' },
  { value: 'globe', label: 'Globe' },
  { value: 'database', label: 'Base de données' },
  { value: 'cloud', label: 'Cloud' },
  { value: 'server', label: 'Serveur' },
  { value: 'shield', label: 'Sécurité' },
  { value: 'search', label: 'Recherche' },
  { value: 'settings', label: 'Paramètres' },
  { value: 'zap', label: 'Éclair' },
  { value: 'layout', label: 'Layout' },
  { value: 'palette', label: 'Palette' },
  { value: 'tool', label: 'Outil' },
  { value: 'package', label: 'Package' },
  { value: 'cpu', label: 'CPU' },
  { value: 'hard-drive', label: 'Disque dur' },
  { value: 'monitor', label: 'Moniteur' },
  { value: 'terminal', label: 'Terminal' },
  { value: 'git-branch', label: 'Git Branch' },
  { value: 'rocket', label: 'Fusée' },
  { value: 'briefcase', label: 'Mallette' },
  { value: 'shopping-cart', label: 'Panier' },
  { value: 'credit-card', label: 'Carte bancaire' },
  { value: 'bar-chart', label: 'Graphique' },
  { value: 'trending-up', label: 'Tendance montante' },
  { value: 'users', label: 'Utilisateurs' },
  { value: 'user-check', label: 'Utilisateur vérifié' },
  { value: 'message-square', label: 'Message' },
  { value: 'mail', label: 'Email' },
  { value: 'phone', label: 'Téléphone' },
  { value: 'video', label: 'Vidéo' },
  { value: 'camera', label: 'Caméra' },
  { value: 'image', label: 'Image' },
  { value: 'file-text', label: 'Document' },
  { value: 'folder', label: 'Dossier' },
  { value: 'archive', label: 'Archive' },
  { value: 'bookmark', label: 'Signet' },
  { value: 'star', label: 'Étoile' },
  { value: 'heart', label: 'Cœur' },
  { value: 'thumbs-up', label: 'Pouce levé' },
  { value: 'check-circle', label: 'Cercle validé' },
  { value: 'alert-circle', label: 'Alerte' },
  { value: 'info', label: 'Information' },
  { value: 'help-circle', label: 'Aide' },
  { value: 'lock', label: 'Cadenas' },
  { value: 'unlock', label: 'Déverrouillé' },
  { value: 'key', label: 'Clé' },
  { value: 'eye', label: 'Œil' },
  { value: 'eye-off', label: 'Œil fermé' },
];
